import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/ui/index.scss'
import './globals.scss'
import '@fortawesome/fontawesome-free/css/all.min.css'
import { Navbar } from '../components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AOE SUP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
